version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: check for skipCI flag in changelog file
          command: ./ci/check-changelog-for-skip-ci.sh
      - run:
          name: Generate config
          # if SKIP_CI=true, use the skipped_config.yml which is a no-op check that
          # passes everything, and will satisfy GitHub's "Mandatory Check" list.
          # If it's any other value, do not skip tests, and instead use the standard
          # testing config found in ci_config.yml.
          command: |
            if [[ $(cat ./skip-ci.txt | grep "SKIP_CI=true" | wc -l) = "1" ]]; then
              echo "Skipping CI, using the skip file"
              cat ./.circleci/skipped_config.yml > ./.circleci/chosen_config.yml
            else
              cat ./.circleci/ci_config.yml > ./.circleci/chosen_config.yml
            fi
      - continuation/continue:
          configuration_path: ./.circleci/chosen_config.yml
workflows:
  setup:
    jobs:
      - setup