version: 2.1
jobs:
  check-skip-tests:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: check for skipCI flag in changelog file
          command: ./ci/check-changelog-for-skip-ci.sh
      - run:
          name: print the output
          command: |
            cat ./skip-ci.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./skip-ci.txt
  unit-tests:
    parallelism: 4
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: check if skip artifact transferred
          command: ls -la /tmp/workspace && cat /tmp/workspace/skip-ci.txt
      - checkout
      - run:
          name: run unit tests
          command: |
            echo "Starting 30 seconds of 'unit testing'..." && sleep 30 && echo "Ok done"
  all-tests:
    parameters:
      platform_variant:
        type: string
      modifier:
        type: string
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: e2e tests
          environment:
            PLATFORM_VARIANT: << parameters.platform_variant >>
            MODIFIER: << parameters.modifier >>
          command: |
            echo "Starting 30 seconds of 'unit testing' for platform: $PLATFORM_VARIANT and modifier $MODIFIER..." && sleep 30 && echo "Ok done"
workflows:
  build:
    jobs:
      - check-skip-tests
      - unit-tests:
          requires:
            - check-skip-tests
      - all-tests:
          requires:
            - check-skip-tests
          matrix:
            parameters:
              platform_variant:
                - "platform-a"
                - "platform-b"
              modifier:
                - "no-modifier"
                - "modifier-1"