name: pull_request

on:
  pull_request:


jobs:
  skip-the-tests:
    name: skip-the-tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Skip checks
        run: |
          ./ci/check-changelog-for-skip-ci.sh
      - name: Skip Result
        run: |
          echo "Will CI be skipped? - ${{ env.SKIP_CI }}"
      - name: Upload SKIP_CI result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: skip-ci-${{ github.sha }}
          path: skip-ci.txt
          retention-days: 1
  run-the-tests:
    name: run-tests
    runs-on: ubuntu-18.04
    needs: skip-the-tests
    strategy:
      fail-fast: false
      matrix:
        project:
        - 'first-thing'
        - 'second-thing'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Check for Skip CI Flag
        uses: actions/download-artifact@v2
        with:
          name: skip-ci-${{ github.sha }}
      - name: Skip Result
        run: |
          cat skip-ci.txt >> $GITHUB_ENV 
          echo "Will CI be skipped? - ${{ env.SKIP_CI }}"
      - name: Run test suite
        if: ${{ env.SKIP_CI == false }} # only run if skip ci is not truthy
        # Fake long tests
        run: |
          echo "Starting 2 minutes of 'testing'..." && sleep 120 && echo "Ok done"
